myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from mytracker import views


extra_patterns = [
    path('', views.projects, name="projects"),
    path(
        '<int:list_id>/<str:list_slug>/',
        views.list_detail,
        name='list_detail'),
    path(
        'task/<int:task_id>/',
        views.task_detail,
        name='task_detail'),

    path(
        'toggle_done/<int:task_id>/',
        views.toggle_done,
        name='task_toggle_done'),
    path(
        '<int:list_id>/<str:list_slug>/completed/',
        views.list_detail,
        {'view_completed': True},
        name='list_detail_completed'),
    path(
        '<int:list_id>/<str:list_slug>/delete/',
        views.del_list,
        name="del_list"),

    path(
        'reorder_tasks/',
        views.reorder_tasks,
        name="reorder_tasks"),

    path(
        'delete/<int:task_id>/',
        views.delete_task,
        name='delete_task'),

    path(
        'mine/',
        views.list_detail,
        {'list_slug': 'mine'},
        name="mine"),
    path(
        'add_list/',
        views.add_list,
        name="add_list"),
    path(
        'update_task/<int:task_id>',
        views.update_task,
        name='update_task'),
    path(
        'search/',
        views.search,
        name="search"),
    path(
        'login/',
        views.signup,
        name="signup"),
]


urlpatterns = [
    path('', TemplateView.as_view(template_name='resources/home.html'), name='home'),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('todo/', include(extra_patterns)),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

mytracker/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import Group
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from datetime import datetime
from tracker.task import Task as LibTask

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField(default='',)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, default='',)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Projects"

        # Prevents (at the database level) creation of two lists with the same slug in the same group
        unique_together = ("group", "slug")


class Task(models.Model):
    name = models.CharField(max_length=256, blank=True, null=True)
    task_list = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    host = models.CharField(max_length=256, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    priority = models.PositiveIntegerField(default=3, null=True)

    parent = models.IntegerField(default=-1)
    create_time = models.DateTimeField(default='1998-12-08 0:00')
    change_time = models.DateTimeField(default='1998-12-08 0:00')
    time_last_copy = models.DateTimeField(default='1998-12-08 0:00')
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)
    period = models.CharField(max_length=128, blank=True, null=True)

    subtasks = models.TextField(blank=True)
    links = models.TextField(blank=True)
    admins = models.TextField(blank=True)
    members = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('task_detail', kwargs={'task_id': self.id, })

        # Auto-set the Task creation / completed date

    def save(self, **kwargs):
        # If Task is being marked complete, set the completed_date
        if self.completed:
            self.completed_date = datetime.now()
        super(Task, self).save()


class DjangoStorage:

    @staticmethod
    def save_task(task):
        new_task = Task.objects.get(id=task.key)
        if new_task:
            new_task.name = task.name
            new_task.host = task.host
            if task.parent:
                new_task.parent = task.parent
            new_task.priority = task.priority
            if task.creation_date:
                new_task.create_time = task.creation_date
            else:
                new_task.create_time = str(datetime.now().strftime("%Y-%m-%d %H:%M"))

            if task.changed_date:
                new_task.change_time = task.changed_date
            else:
                new_task.change_time = str(datetime.now().strftime("%Y-%m-%d %H:%M"))

            if task.admins:
                new_task.admins = '|'.join(task.admins)
            else:
                new_task.admins = ''

            if task.time_last_copy:
                new_task.time_last_copy = task.time_last_copy
            else:
                new_task.time_last_copy = str(datetime.now().strftime("%Y-%m-%d %H:%M"))

            if task.members:
                new_task.members = '|'.join(task.members)
            else:
                new_task.members = ''

            if task.links:
                new_task.links = '|'.join(task.links)
            else:
                new_task.links = ''

            str_sub = [str(x) for x in task.subtasks]

            print(str_sub)

            if str_sub:
                new_task.subtasks = '|'.join(str_sub)
            else:
                new_task.subtasks = ''

            new_task.description = task.description
            new_task.start_time = task.start_time
            new_task.end_time = task.deadline
            new_task.period = task.period
            new_task.task_list = get_object_or_404(Project, id=task.project)
            new_task.save()

    @staticmethod
    def get_task(key_task):
        try:
            task = Task.objects.get(id=key_task)
            lib_task = LibTask(key=key_task, creation_date=task.create_time, changed_date=task.change_time)
            lib_task.name = task.name
            lib_task.host = task.host
            if task.parent != -1:
                lib_task.parent = task.parent
            lib_task.priority = task.priority
            lib_task.status = task.completed
            lib_task.description = task.description
            lib_task.start_time = task.start_time
            lib_task.deadline = task.end_time
            lib_task.project = task.task_list.id
            if not task.period:
                lib_task.period = ''
            else:
                lib_task.period = task.period
            lib_task.time_last_copy = task.time_last_copy

            if task.admins != '':
                lib_task.admins = task.admins.split('|')

            if task.members != '':
                lib_task.members = task.members.split('|')

            if task.links != '':
                lib_task.links = task.links.split('|')

            if task.subtasks != '':
                lib_task.subtasks = task.subtasks.split('|')

            return lib_task
        except:
            return


class Comment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now)
    body = models.TextField(blank=True)

    def snippet(self):
        # Define here rather than in __str__ so we can use it in the admin list_display
        return "{author} - {snippet}...".format(author=self.author, snippet=self.body[:35])

    def __str__(self):
        return self.snippet

templates/resources/add_project.html
{% extends "base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Add a new project{% endblock %}
{% block content %}

  <h2>Add a list:</h2>

  <form action="" method="post">
    {% csrf_token %}

    <div class="form-group">
      <label for="id_name">List Name</label>
      <input type="text" class="form-control" id="id_name" name="name" aria-describedby="inputNameHelp" placeholder="">
      <small id="inputNameHelp" class="form-text text-muted">The full display name for this list.</small>
    </div>
    <div class="form-group">
      <label for="id_group">Group</label>
      {{form.group}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/resources/del_project.html
{% extends "base.html" %}
{% block title %}Delete list{% endblock %}

{% block content %}
  {% if user.is_staff %}
  <h1>Delete entire list: {{ task_list.name }} ?</h1>

  <p>Category tally:</p>

  <ul>
    <li>Incomplete: {{ task_count_undone }} </li>
    <li>Complete: {{ task_count_done }} </li>
    <li>
      <strong>Total: {{ task_count_total }}</strong>
    </li>
  </ul>

  <p> ... all of which will be irretrievably
    <strong>blown away</strong>. Are you sure you want to do that?</p>

  <form action="" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <input type="hidden" name="task_list" value="{{ task_list.id }}">
    <p>
      <a href="{% url 'list_detail' task_list.id task_list.slug %}" class="btn btn-success">Return to list: {{ task_list.name }}</a>
      <input type="submit" name="delete-confirm" value="Do it! &rarr;" class="btn btn-danger">
    </p>
  </form>


{% else %}
  <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>
{% endif %} {% endblock %}

templates/resources/home.html
{% extends "base.html" %} {% block title %}django-todo{% endblock %}

{% block content %}

  <h1>My Tracker</h1>

  <p>
    My Tracker is a
    <i>pluggable</i>, multi-user, multi-group, multi-list todo system.

  <p>
         Planning to go out?
     Don't miss a beat with My Tracker.

  </p>

{% endblock %}

templates/resources/info_task.html
{% extends "base.html" %}

{% block title %}Info task{% endblock title %}

{% block load_script %}

{% endblock load_script %}

{% block content %}


    <h5>ID: {{task.id}}</h5><br>

    <form action="{% url 'update_task' task_id %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label>Name:</label><br>

        <input value="{{task.name}}" disabled id="input_name" class="form-control" name="ch_name"><br>

        {% if block_button == False %}
        <button type="button" style="" onclick="Active('input_name', 'button_name_ok', 'button_name_red')" id="button_name_red" class="info_button">
            <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
        </button>

        <button style="visibility:hidden;"
                onclick="Disabled('input_name', 'button_name_ok', 'button_name_red')" id="button_name_ok" class="info_button">
            <span class="oi oi-check" title="check" aria-hidden="true"></span>
        </button><br>
        {% endif %}
    </div>


    <div class="form-group">
        <label>Description:</label><br>
        <textarea style="height:150%; width: 80%" name="ch_descr" cols="40" rows="10" class="form-control" id="input_descr" disabled>{{task.description}}</textarea>

        {% if block_button == False %}
        <button type="button" onclick="Active('input_descr', 'button_descr_ok', 'button_descr_red')" id="button_descr_red" class="info_button">
            <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
        </button>

        <button style="visibility:hidden" onclick="Disabled('input_descr', 'button_descr_ok', 'button_descr_red')"
                id="button_descr_ok" class="info_button">
            <span class="oi oi-check" title="check" aria-hidden="true"></span>
        </button><br>
        {% endif %}
    </div>


    <div class="form-group">
        <label>Priority:</label><br>
        <select name="ch_priority" class="custom-select" id="input_priority" disabled>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
        </select>

        {% if block_button == False %}
        <button type="button" onclick="Active('input_priority', 'button_priority_ok', 'button_priority_red')" id="button_priority_red"
                class="info_button">
            <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
        </button>

        <button style="visibility:hidden" onclick="Disabled('input_priority', 'button_priority_ok', 'button_priority_red')"
                id="button_priority_ok" class="info_button">
            <span class="oi oi-check" title="check" aria-hidden="true"></span>
        </button><br>
        {% endif %}
    </div>


    <div class="form-group">
        <label>Status: </label><br>
        <select name="ch_status" id="input_status" class="custom-select" disabled>
            <option value=""></option>
            <option value="complete">complete</option>
            <option value="process">process</option>
        </select>

        {% if block_button == False %}
        <button type="button" onclick="Active('input_status', 'button_status_ok', 'button_status_red')" id="button_status_red"
                class="info_button">
            <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
        </button>

        <button style="visibility:hidden" onclick="Disabled('input_status', 'button_status_ok', 'button_status_red')"
                id="button_status_ok" class="info_button">
            <span class="oi oi-check" title="check" aria-hidden="true"></span>
        </button><br>
        {% endif %}
    </div>


    <script>
        function Set_def_on_select(select_value, id_select){
            select = document.getElementById(id_select);
            for (var i = 0; i < select.options.length; i++) {
                if (select.options[i].value == select_value) {
                    select.selectedIndex = i;
                }
            }
        }
        Set_def_on_select({{task.priority}}, 'input_priority');
        Set_def_on_select("{{task.status}}", 'input_status');
    </script>


    <div class="form-group">
        <label>Start:</label><br>
        <input name="date_start" class="form-control" type="date" value="{{start_date}}" id="start_date" disabled onblur="ValidateTime('end_date', 'start_date')">
        <input name="time_start" class="form-control" type="time" value="{{start_time}}" id="start_time" disabled>

        {% if block_button == False %}
        <button type="button" onclick="Active_time('start_date', 'start_time', 'button_start_ok', 'button_start_red')" id="button_start_red"
                class="info_button">
            <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
        </button>

        <button style="visibility:hidden" onclick="Disabled_time('start_date', 'start_time', 'button_start_ok', 'button_start_red')"
                id="button_start_ok" class="info_button">
            <span class="oi oi-check" title="check" aria-hidden="true"></span>
        </button><br>
        {% endif %}
    </div>


    <div class="change_time" >
        <label>End:</label><br>
        <input name="date_end" class="form-control" type="date" value="{{end_date}}" id="end_date" disabled onblur="ValidateTime('end_date', 'start_date')">
        <input name="time_end" class="form-control" type="time" value="{{end_time}}" id="end_time" disabled>

        {% if block_button == False %}
        <button type="button" onclick="Active_time('end_date', 'end_time', 'button_end_ok', 'button_end_red')" id="button_end_red"
                class="info_button">
            <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
        </button>

        <button style="visibility:hidden" onclick="Disabled_time('end_date', 'end_time', 'button_end_ok', 'button_end_red')"
                id="button_end_ok" class="info_button">
            <span class="oi oi-check" title="check" aria-hidden="true"></span>
        </button><br>
        {% endif %}
    </div>


    <div class="change_name_type">
        <label>Period:</label><br>

        <input pattern="^[0-9]/[0-9]/[0-9]/[0-9]" style="width:120px" value="{{task.period}}" name="ch_period" disabled id="input_period" class="form-control"><br>

        {% if block_button == False %}
        <button type="button"  onclick="Active('input_period', 'button_period_ok', 'button_period_red')" id="button_period_red" class="info_button">
            <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
        </button>

        <button style="visibility:hidden"
                onclick="Disabled('input_period', 'button_period_ok', 'button_period_red')" id="button_period_ok" class="info_button">
            <span class="oi oi-check" title="check" aria-hidden="true"></span>
        </button><br>
        {% endif %}
    </div>


    <label>Creat time:  {{task.create_time}} </label>
    <label>Last change time:  {{task.change_time}} </label>
    </form>


    <form action="." method="post" style="margin-bottom: 40px">
        {% csrf_token %}
        <div>
            <h5>Admins</h5>
            <input class="form-control" name="new_admin" style="height:30px; width: 140px">
            {% if block_button == False %}
            <button name="add_admin" class="info_button" style="height:30px; width:30px; position: relative; top:-30px; left:150px;">
                <span class="oi oi-plus" title="plus" aria-hidden="true" style="top: 3px"></span>
            </button>
            {% endif %}


                <div>
                    {% for admin in admins %}
                    <div style="display:inline; position:relative; top: -30px">
                        {{ admin }}
                        {% if block_button == False %}
                        <button name="remove_admin" value="{{admin}}" class="removed_button">
                            <span class="oi oi-x" title="x" aria-hidden="true" style=""></span>
                        </button>
                        {% endif %}
                        <label>  </label>
                    </div>
                    {% endfor %}
                </div>
        </div>

        <div>
            <h5>Members</h5>
            <input class="form-control" name="new_member" style="height:30px; width: 140px">
            {% if block_button == False %}
            <button name="add_member" class="info_button" style="height:30px; width:30px; position: relative; top:-30px; left:150px;">
                <span class="oi oi-plus" title="plus" aria-hidden="true" style="top: 3px"></span>
            </button>
            {% endif %}
                <div>
                    {% for member in members %}
                    <div style="display:inline; position:relative; top: -30px">
                        {{ member }}
                        {% if block_button == False %}
                        <button name="remove_member" value="{{member}}" class="removed_button">
                            <span class="oi oi-x" title="x" aria-hidden="true" style=""></span>
                        </button>
                        {% endif %}
                        <label>  </label>
                    </div>
                    {% endfor %}
                </div>
        </div>

        <div>
            <h5>Linked tasks</h5>
            <input class="form-control" name="new_link" style="height:30px; width: 140px">
            {% if block_button == False %}
            <button name="add_link" class="info_button" style="height:30px; width:30px; position: relative; top:-30px; left:150px;">
                <span class="oi oi-plus" title="plus" aria-hidden="true" style="top: 3px"></span>
            </button>
            {% endif %}

            <table class="table" style="position:relative; top: 10px">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th/>
                    <th/>
                </tr>
                </thead>
                <tbody>
                    {% for link in links %}
                    <tr>
                        <td>{{ link.id }}</td>
                        <td>{{ link.name }}</td>
                        <td valign="middle">
                            <button class="info_button" type="submit" value="{{link.id}}" name="info_button">
                                <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
                            </button>
                        </td>
                        <td valign="middle">
                            {% if block_button == False %}
                            <button name="remove_link" value="{{link.id}}" class="removed_button">
                                <span class="oi oi-x" title="x" aria-hidden="true" style=" font-size: 100%;"></span>
                            </button>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div>
            <h5 style="position: relative; top: 30px">Subtasks</h5>
            {% if block_button == False %}
             <button class="btn btn-primary" id="AddTaskButton" type="button" style="height:30px;position: relative; left:100px;"
              data-toggle="collapse" data-target="#AddEditTask" >Add Task</button>

            {# Task edit / new task form #}
            {% include 'resources/task_edit.html' %}
            {% endif %}

            <table class="table" style="position:relative; top: 40px">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th/>
                </tr>
                </thead>
                <tbody>
                    {% for task in subtasks %}
                    <tr>
                        <td>{{ task.id }}</td>
                        <td>{{ task.name }}</td>
                        <td valign="middle">
                            <button class="info_button" type="submit" value="{{task.id}}" name="info_button">
                                <span class="oi oi-pencil" title="pencil" aria-hidden="true"></span>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </form>

  <h5>Add comment</h5>
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <textarea class="form-control" name="comment-body" rows="3"></textarea>
    </div>
    <input class="btn btn-sm btn-primary" type="submit" name="add_comment" value="Add Comment">
  </form>

  <div class="task_comments mt-4">
    {% if comment_list %}
      <h5>Comments on this task</h5>
      {% for comment in comment_list %}
        <p>
          <strong>
            {{ comment.author.username }},
            {{ comment.date|date:"F d Y P" }}
          </strong>
        </p>
        {{ comment.body|safe|urlize|linebreaks }}
      {% endfor %}
    {% else %}
        <h5>No comments (yet).</h5>
    {% endif %}
  </div>


    <form action="{% url 'projects'%}" method="get" class="button_on_tasks_view">
        <button style="width:85px; height:35px" class="btn btn-secondary" type="submit">Back</button>
    </form>


    <script src="/static/js/scripts.js"></script>
{% endblock content %}

templates/resources/project_details.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Todo List: {{ task_list.name }}{% endblock %}

{% block content %}

  {% if list_slug != "mine" %}
    <button class="btn btn-primary" id="AddTaskButton" type="button"
      data-toggle="collapse" data-target="#AddEditTask" >Add Task</button>

    {# Task edit / new task form #}
    {% include 'resources/task_edit.html' %}
    <hr />
  {% endif %}

  {% if tasks %}
    {% if list_slug == "mine" %}
      <h1>Tasks assigned to me (in all groups)</h1>
    {% else %}
      <h1>{{ view_completed|yesno:"Completed tasks, Tasks" }} in "{{ task_list.name }}"</h1>
      <p><small><i>In workgroup "{{ task_list.group }}" - drag rows to set priorities.</i></small></p>
    {% endif %}

      <table class="table" id="tasktable">
        <tr class="nodrop">
          <th>Task</th>
          <th>Created</th>
          <th>Due on</th>
          <th>Owner</th>
          <th>Priority</th>
          <th>Mark</th>
        </tr>

        {% for task in tasks %}
          <tr id="{{ task.id }}">
            <td>
                <a href="{% url 'task_detail' task.id %}">{{ task.name|truncatewords:10 }}</a>
            </td>
            <td>
                {{ task.create_time|date:"m/d/Y" }}
            </td>
            <td>
              <span {% if task.overdue_status %}class="overdue"{% endif %}>
                {{ task.end_time|date:"m/d/Y" }}
              </span>
            </td>
            <td>
              {{ task.host }}
            </td>
            <td>
              {{ task.priority }}
            </td>
            <td>
                <a href="{% url "task_toggle_done" task.id %}" class="btn btn-info btn-sm">
                  {% if view_completed %}
                    Not Done
                  {% else %}
                    Done
                  {% endif %}
                </a>

                <a href="{% url "delete_task" task.id %}" class="btn btn-danger btn-sm">Delete</a>
              </td>
          </tr>
        {% endfor %}
      </table>

      {% include 'resources/toggle_delete.html' %}

  {% else %}
    <h4>No tasks on this list yet (add one!)</h4>
    {% include 'resources/toggle_delete.html' %}

  {% endif %}

{% endblock %}

{% block extra_js %}
  <script src="{% static 'js/jquery.tablednd.js' %}" type="text/javascript"></script>

  <script type="text/javascript">
    function order_tasks(data) {
      // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
      // data in a list. We pass that list as an object ("data") to a Django view
      // to save new priorities on each task in the list.
      $.post("{% url 'reorder_tasks' %}", data, "json");
      return false;
    };

    $(document).ready(function() {
      // Initialise the task table for drag/drop re-ordering
      $("#tasktable").tableDnD();

      $('#tasktable').tableDnD({
        onDrop: function(table, row) {
          order_tasks($.tableDnD.serialize());
        }
      });

    });

    // When adding a task, change the text of the Add Task button
    function handleClick()
    {
        console.log(this.innerHTML);
        this.innerHTML = (this.innerHTML == 'Add Task' ? 'Cancel' : 'Add Task');
    }
    document.getElementById('AddTaskButton').onclick=handleClick;
  </script>
{% endblock extra_js %}

templates/resources/projects.html
{% extends "base.html" %}

{% block title %}{{ list_title }} Todo Lists{% endblock %}

{% block content %}
  <h1>Projects</h1>

  <p>{{ task_count }} tasks in {{ list_count }} list{{ list_count|pluralize }}</p>

  {% regroup lists by group as section_list %}
  {% for group in section_list %}
    <h3>Group: {{ group.grouper }}</h3>
    <ul class="list-group mb-4">
      {% for task in group.list %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'list_detail' task.id task.slug %}">{{ task.name }}</a>
        <span class="badge badge-primary badge-pill">{{ task.task_set.count }}</span>
      </li>
      {% endfor %}
    </ul>
  {% endfor %}

  <div class="mt-3">

    {% if user.is_staff %}
      <a href="{% url 'add_list' %}" class="btn btn-primary">Create new project</a>
    {% else %}
      <a href="" class="btn btn-primary disabled">If you were staff, you could create a new list</a>
    {% endif %}
      
  </div>

{% endblock %}

templates/resources/search_results.html
{% extends "base.html" %}

{% block title %}Search results{% endblock %}
{% block content_title %}<h2 class="page_title">Search</h2>{% endblock %}

{% block content %}
  {% if found_tasks %}
  <h2>{{found_tasks.count}} search results for term: "{{ query_string }}"</h2>
  <div class="post_list">
    {% for f in found_tasks %}
    <p>
      <strong>
        <a href="{% url 'task_detail' f.id %}">{{ f.name }}</a>
      </strong>
      <br />
      <span class="minor">
        In list:
        <a href="{% url 'list_detail' f.task_list.id f.task_list.slug %}">
          {{ f.task_list.name }}
        </a>
        <br /> Assigned to: {% if f.host %}{{ f.host }}{% else %}Anyone{% endif %}
        <br /> Complete: {{ f.completed|yesno:"Yes,No" }}
      </span>
    </p>
    {% endfor %}
  </div>
  {% else %}
    <h2> No results to show, sorry.</h2>
  {% endif %}
{% endblock %}

templates/resources/task_edit.html
{# Form used by both Add Task and Edit Task views #}

<form action="" name="add_task" method="post">
  {% csrf_token %}


  <div id="AddEditTask" class="collapse mt-3">
        <input name="parent_task" value="{{task_id}}" style="visibility: hidden" >
        <table>
            <tr>
                <td height="120px" width="12%"><label>Name task</label></td>
                <td><input class="form-control" type="text" name="name_task" required/></td>
                <td width="10%" align="center"><label>Priority</label></td>
                <td width="100px">
                    <select style="width:60px" name="priority_task" class="custom-select">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td align="center"><label>Description</label></td>
                <td><textarea name="description" cols="40" rows="10" class="form-control"></textarea></td>
            </tr>
            <tr>
                <td height="120px"><label>Start time</label></td>
                <td>
                    <table>
                        <tr>
                            <td><input name="date_start" class="form-control" type="date" id="add_start_date" onblur="ValidateTime('add_end_date', 'add_start_date')"></td>
                            <td><input name="time_start" class="form-control" type="time" id="add_start_time"></td>
                        </tr>
                    </table>
                <td align="center"><label>End time</label></td>
                <td>
                    <table>
                        <tr>
                            <td><input name="date_end" class="form-control" type="date" id="add_end_date" onblur="ValidateTime('add_end_date', 'add_start_date')"></td>
                            <td><input name="time_end" class="form-control" type="time" id="add_end_time"></td>
                        </tr>
                    </table>
                </td>
                <td align="center"><label>Period</label></td>
                <td><input pattern="^[0-9]/[0-9]/[0-9]/[0-9]" name="period" class="form-control" type="text" placeholder="m/d/H/M"></td>
                <td></td>
            </tr>
        </table>

    <p>
      <input type="submit" name="create" value="Submit" class="btn btn-primary">
    </p>

  </div>
</form>